import { Geist } from "next/font/google";
import { NavbarProvider } from "@/context/navbar";
import {displayLang} from "@/lib/lang";
import axios from "@/lib/axios";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

    const lang = await displayLang();

    const logoResp = (await axios.get("logos")).data;
    const navbarResp = (await axios.get(`navbars?lang=${lang}`)).data;
    const langResp = (await axios.get("languages")).data;
    const footerLabelResp = (await axios.get(`footer-labels?lang=${lang}`)).data[0];

  return (
    <html lang="en">  
      <body className={`${geistSans.variable}`}>
        <NavbarProvider>
          <Header headerData={{logoResp, navbarResp, langResp}} lang={lang} />
          <main>{children}</main>
          <Footer footerData={footerLabelResp} />
        </NavbarProvider>
      </body>
    </html>
  );
}
